In [1]:
import torch

In [5]:
device = 'cuda' if torch.cuda.is_available() else "cpu"
device

'cpu'

In [7]:
my_tensor = torch.tensor([[1,4],[2,5]], dtype = torch.float32,device=device)
my_tensor

tensor([[1., 4.],
        [2., 5.]])

In [10]:
my_tensor.ndim, my_tensor.dtype,my_tensor.device,my_tensor.shape,my_tensor.size

(2,
 torch.float32,
 device(type='cpu'),
 torch.Size([2, 2]),
 <function Tensor.size>)

In [12]:
x = torch.empty((2,3))
x

tensor([[8.3966e-07, 5.2898e-08, 4.3201e-05],
        [2.1495e-04, 1.0487e+21, 8.3084e-10]])

In [14]:
y = torch.zeros((3,3))
y

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
o = torch.ones((2,3))
o

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
randoms = torch.randn((3,2))
randoms

tensor([[ 0.5308, -0.0055],
        [ 0.8271, -1.0454],
        [-0.6789,  0.1636]])

In [19]:
diag_matrix=torch.eye(3,3)
diag_matrix

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [20]:
torch.arange(start=1,end=5, step=1)

tensor([1, 2, 3, 4])

In [23]:
torch.linspace(start=0.1,end=2,steps=10)

tensor([0.1000, 0.3111, 0.5222, 0.7333, 0.9444, 1.1556, 1.3667, 1.5778, 1.7889,
        2.0000])

In [24]:
torch.empty((2,5)).normal_(mean=0,std=1)

tensor([[ 0.4583,  0.0274,  0.9185, -1.3422, -0.2874],
        [-0.1798,  0.0487, -0.1626,  0.9382, -0.8184]])

In [26]:
torch.empty((2,5)).uniform_(0,1)

tensor([[0.5308, 0.8261, 0.3960, 0.5801, 0.9603],
        [0.5449, 0.4943, 0.8511, 0.9417, 0.0282]])

In [28]:
torch.diag(torch.randn(3))

tensor([[-0.8158,  0.0000,  0.0000],
        [ 0.0000,  0.4763,  0.0000],
        [ 0.0000,  0.0000,  0.6569]])

# initialize a tensor and convert to different types

In [29]:
tensor = torch.arange(5)
tensor.dtype

torch.int64

In [31]:
tensor.bool()

tensor([False,  True,  True,  True,  True])

In [32]:
tensor.short()

tensor([0, 1, 2, 3, 4], dtype=torch.int16)

In [34]:
tensor.long().dtype

torch.int64

In [36]:
tensor.half()

tensor([0., 1., 2., 3., 4.], dtype=torch.float16)

In [38]:
tensor.float().dtype

torch.float32

In [39]:
tensor.double()

tensor([0., 1., 2., 3., 4.], dtype=torch.float64)

# Array to tensor

In [40]:
import numpy as np
np_arr= np.zeros((5,5))
np_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [41]:
tensor = torch.from_numpy(np_arr)
tensor

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)

In [42]:
np_back_arr=tensor.numpy()
np_back_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Tensor Math

In [46]:
x = torch.tensor([1,2,3])
y = torch.tensor([9,8,7])
# add
z1 = torch.empty(3)
torch.add(x,y,out=z1)
print(z1,z1.dtype)

tensor([10., 10., 10.]) torch.float32


In [47]:
z2 = torch.add(x,y)
z2,z2.dtype

(tensor([10, 10, 10]), torch.int64)

In [48]:
# minus
z3 = x-y
# div
z4 = torch.true_divide(x,y) #element wise div if of equal shape
z4

tensor([0.1111, 0.2500, 0.4286])

In [49]:
# inplace ops
t = torch.zeros(3)
t.add_(x) #to perform inplace ops add _ next to it
print(t)
t +=y
print(t)

tensor([1., 2., 3.])
tensor([10., 10., 10.])


In [50]:
# exp
z = x.pow(2)
z

tensor([1, 4, 9])

In [51]:
# comparison
z = x>0
z

tensor([True, True, True])

In [52]:
z=x<0
z

tensor([False, False, False])

In [61]:
# matmul
x1=torch.rand((5,5))
x2=torch.rand((2,5))


In [62]:
z = torch.mm(x2,x1)
z

tensor([[0.8419, 0.4973, 0.2199, 0.5052, 1.1100],
        [1.3150, 0.9877, 0.5900, 1.0529, 1.4712]])

In [63]:
z = x2.mm(x1)
z

tensor([[0.8419, 0.4973, 0.2199, 0.5052, 1.1100],
        [1.3150, 0.9877, 0.5900, 1.0529, 1.4712]])

In [66]:
# matrix exp
matrix_exp = torch.rand((5,5))
matrix_exp.matrix_power(2)

tensor([[1.9110, 1.8325, 1.9540, 1.4696, 0.9139],
        [1.8131, 1.7378, 1.6077, 1.0749, 0.7749],
        [1.6260, 1.7577, 1.5402, 1.0704, 0.8047],
        [1.6257, 1.9847, 1.9196, 1.6145, 1.2190],
        [1.5005, 1.7046, 1.4367, 0.9821, 0.8368]])

In [68]:
matrix_exp.pow(2)

tensor([[0.7275, 0.3049, 0.7322, 0.3694, 0.0028],
        [0.6702, 0.5229, 0.3530, 0.0377, 0.0695],
        [0.4126, 0.5392, 0.1148, 0.0674, 0.3158],
        [0.0729, 0.2227, 0.9374, 0.9871, 0.1247],
        [0.1135, 0.7937, 0.1120, 0.1162, 0.2756]])

In [70]:
x.dot(y)

tensor(46)

# Batch matrix mul

In [71]:
batch = 32
n=10
m=20
p=30
tensor1=torch.rand((batch,n,m))
tensor2=torch.rand((batch,m,p))
out_bmm = tensor1.bmm(tensor2)

In [73]:
out_bmm.shape

torch.Size([32, 10, 30])

# Broadcasting

In [74]:
x1 = torch.rand((5,5))
x2 = torch.rand((1,5))
z= x1-x2


# Tensor indexing

In [76]:
features = 25
x = torch.rand((batch,features))
x[0,:].shape

torch.Size([25])

In [80]:
x[:,1]

tensor([0.1503, 0.5392, 0.1558, 0.7343, 0.5572, 0.5679, 0.5668, 0.0590, 0.5395,
        0.1053, 0.1611, 0.5076, 0.0249, 0.3401, 0.0041, 0.0842, 0.6350, 0.9701,
        0.7889, 0.5110, 0.9249, 0.5071, 0.4058, 0.5778, 0.6356, 0.5936, 0.9608,
        0.2069, 0.8310, 0.8969, 0.5772, 0.7901])

In [81]:
x[:10,2]

tensor([0.5391, 0.4097, 0.6481, 0.3493, 0.2760, 0.9153, 0.6581, 0.8090, 0.9548,
        0.8607])

In [83]:
x = torch.arange(10)
indices = [1,2,5]
print(x[indices])

tensor([1, 2, 5])


In [89]:
print(x[(x<2) != (x>5)])

tensor([0, 1, 6, 7, 8, 9])


In [92]:
x[x.remainder(2)==0]

tensor([0, 2, 4, 6, 8])

In [93]:
torch.where(x>4,x-1,x*2) #where x>4 set x-1 other wise do x*2

tensor([0, 2, 4, 6, 8, 4, 5, 6, 7, 8])

In [94]:
x.numel()

10

# tensor reshapeing

In [104]:
x = torch.arange(15)
x_3x5 = x.view((3,5)) # for contiguous tensors means which are\contiguously stored in memroy

In [105]:
x_3x5

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [97]:
x_5x2 = x.reshape((5,2))
x_5x2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [106]:
y = x_2x5.t()
y

tensor([[ 0,  5, 10],
        [ 1,  6, 11],
        [ 2,  7, 12],
        [ 3,  8, 13],
        [ 4,  9, 14]])